import Head from 'next/head'
import Link from 'next/link'
import Navbar from '../components/Navbar'
import Hero from '../pages/sections/Hero'
import Footer from '../components/Footer'

function Home () {
  return (
    <div className='home'>
      <Head>
        <title>Number One Fan</title>
        <meta name='description' content='Generated by create next app' />
        <Link rel='icon' href='./public/favicon.ico' />
      </Head>
      <body onclick='PlayAudio'>
        <Navbar />
        <Hero />
        <Footer />
      </body>
    </div>
  )
}

export default Home
